[project]
name = "pyroboplan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "meshcat>=0.3.2",
    "pin>=2.6.18",
    "pinocchio>=0.4.3",
    "pycapacity>=2.1.3",
    "robomeshcat>=1.1.4",
]
